-- ============================================================
-- AVERTISSEMENT — Seed conçu pour un NOUVEAU projet Supabase vierge
-- (ou le mode local). Ne PAS exécuter sur le projet live
-- piavdhrlayfsnrfhqbww (données réelles présentes, trigger
-- handle_new_user durci qui refuserait ces inserts sans metadata
-- conformes).
-- ============================================================

-- ============================================================
-- Seed data for testing RH_Manager (Supabase cloud schema)
-- Run this after applying all migrations 1 -> 4.
--
-- Passwords are generated by pgcrypto's blowfish (bf) which
-- emits $2a$ hashes compatible with BCrypt.checkpw on Dart.
--   * admin@acme.com       / password
--   * hr@acme.com          / password
--   * john.doe@acme.com    / password
--   * jane.smith@acme.com  / password
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. TEST COMPANIES
-- ============================================================

INSERT INTO public.companies (id, name, domain, created_at, updated_at) VALUES
('10000000-0000-0000-0000-000000000001'::uuid, 'Acme Corporation', 'acme.com', NOW(), NOW()),
('10000000-0000-0000-0000-000000000002'::uuid, 'Tech Innovations Ltd', 'techinno.com', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 2. QR CONFIGS (Geofencing & TOTP)
-- ============================================================

INSERT INTO public.qr_configs (
    id,
    company_id,
    rotation_seconds,
    office_lat,
    office_lng,
    radius_meters,
    is_geofencing_enabled,
    is_totp_enabled,
    config_code,
    name,
    active,
    updated_at
) VALUES
(
    '20000000-0000-0000-0000-000000000001'::uuid,
    '10000000-0000-0000-0000-000000000001'::uuid,
    15,
    48.8566,
    2.3522,
    500,
    true,
    true,
    'ACME-QR',
    'Acme HQ',
    true,
    NOW()
),
(
    '20000000-0000-0000-0000-000000000002'::uuid,
    '10000000-0000-0000-0000-000000000002'::uuid,
    15,
    51.5074,
    -0.1278,
    300,
    true,
    true,
    'TECHINNO-QR',
    'TechInno HQ',
    true,
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 3. TEST USERS (profiles created by the auth trigger)
--    The trigger reads raw_user_meta_data->>'name'.
--    encrypted_password uses crypt()/gen_salt('bf') so the hash
--    is a valid bcrypt digest for the plaintext 'password'.
-- ============================================================

-- Admin User
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '30000000-0000-0000-0000-000000000001'::uuid,
    'authenticated',
    'authenticated',
    'admin@acme.com',
    crypt('password', gen_salt('bf', 10)),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"name":"Alex Rivers","company_id":"10000000-0000-0000-0000-000000000001","role":"admin"}',
    NOW(),
    NOW()
) ON CONFLICT DO NOTHING;

-- HR User
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '30000000-0000-0000-0000-000000000002'::uuid,
    'authenticated',
    'authenticated',
    'hr@acme.com',
    crypt('password', gen_salt('bf', 10)),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"name":"Sarah Jenkins","company_id":"10000000-0000-0000-0000-000000000001","role":"hr"}',
    NOW(),
    NOW()
) ON CONFLICT DO NOTHING;

-- Employee User 1
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '30000000-0000-0000-0000-000000000003'::uuid,
    'authenticated',
    'authenticated',
    'john.doe@acme.com',
    crypt('password', gen_salt('bf', 10)),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"name":"John Doe","company_id":"10000000-0000-0000-0000-000000000001","role":"employee"}',
    NOW(),
    NOW()
) ON CONFLICT DO NOTHING;

-- Employee User 2
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '30000000-0000-0000-0000-000000000004'::uuid,
    'authenticated',
    'authenticated',
    'jane.smith@acme.com',
    crypt('password', gen_salt('bf', 10)),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"name":"Jane Smith","company_id":"10000000-0000-0000-0000-000000000001","role":"employee"}',
    NOW(),
    NOW()
) ON CONFLICT DO NOTHING;

-- Safety net: if profiles were not created by the trigger (e.g. seed
-- applied with triggers disabled), create/repair them explicitly.
INSERT INTO public.profiles (id, email, company_id, role, first_name, last_name, status)
VALUES
(
    '30000000-0000-0000-0000-000000000001'::uuid,
    'admin@acme.com',
    '10000000-0000-0000-0000-000000000001'::uuid,
    'admin',
    'Alex',
    'Rivers',
    'active'
),
(
    '30000000-0000-0000-0000-000000000002'::uuid,
    'hr@acme.com',
    '10000000-0000-0000-0000-000000000001'::uuid,
    'hr',
    'Sarah',
    'Jenkins',
    'active'
),
(
    '30000000-0000-0000-0000-000000000003'::uuid,
    'john.doe@acme.com',
    '10000000-0000-0000-0000-000000000001'::uuid,
    'employee',
    'John',
    'Doe',
    'active'
),
(
    '30000000-0000-0000-0000-000000000004'::uuid,
    'jane.smith@acme.com',
    '10000000-0000-0000-0000-000000000001'::uuid,
    'employee',
    'Jane',
    'Smith',
    'active'
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 4. SAMPLE ATTENDANCE LOGS
-- ============================================================

INSERT INTO public.attendance_logs (
    id,
    profile_id,
    company_id,
    date,
    clock_in_time,
    clock_out_time,
    clock_in_lat,
    clock_in_lng,
    clock_out_lat,
    clock_out_lng,
    status,
    qr_token,
    created_at,
    updated_at
) VALUES
-- John Doe - Previous Monday
(
    '40000000-0000-0000-0000-000000000001'::uuid,
    '30000000-0000-0000-0000-000000000003'::uuid,
    '10000000-0000-0000-0000-000000000001'::uuid,
    CURRENT_DATE - INTERVAL '4 days',
    (CURRENT_DATE - INTERVAL '4 days')::timestamptz + INTERVAL '08:30:00',
    (CURRENT_DATE - INTERVAL '4 days')::timestamptz + INTERVAL '17:00:00',
    48.8566,
    2.3522,
    48.8566,
    2.3522,
    'on_time'::public.attendance_status,
    'seeded',
    NOW(),
    NOW()
),
-- John Doe - Tuesday
(
    '40000000-0000-0000-0000-000000000002'::uuid,
    '30000000-0000-0000-0000-000000000003'::uuid,
    '10000000-0000-0000-0000-000000000001'::uuid,
    CURRENT_DATE - INTERVAL '3 days',
    (CURRENT_DATE - INTERVAL '3 days')::timestamptz + INTERVAL '08:45:00',
    (CURRENT_DATE - INTERVAL '3 days')::timestamptz + INTERVAL '17:15:00',
    48.8566,
    2.3522,
    48.8566,
    2.3522,
    'on_time'::public.attendance_status,
    'seeded',
    NOW(),
    NOW()
),
-- Jane Smith - Previous Monday (late arrival)
(
    '40000000-0000-0000-0000-000000000003'::uuid,
    '30000000-0000-0000-0000-000000000004'::uuid,
    '10000000-0000-0000-0000-000000000001'::uuid,
    CURRENT_DATE - INTERVAL '4 days',
    (CURRENT_DATE - INTERVAL '4 days')::timestamptz + INTERVAL '09:05:00',
    (CURRENT_DATE - INTERVAL '4 days')::timestamptz + INTERVAL '17:30:00',
    48.8566,
    2.3522,
    48.8566,
    2.3522,
    'late'::public.attendance_status,
    'seeded',
    NOW(),
    NOW()
),
-- Jane Smith - Tuesday (still clocked in)
(
    '40000000-0000-0000-0000-000000000004'::uuid,
    '30000000-0000-0000-0000-000000000004'::uuid,
    '10000000-0000-0000-0000-000000000001'::uuid,
    CURRENT_DATE - INTERVAL '3 days',
    (CURRENT_DATE - INTERVAL '3 days')::timestamptz + INTERVAL '08:30:00',
    NULL,
    48.8566,
    2.3522,
    NULL,
    NULL,
    'on_time'::public.attendance_status,
    'seeded',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================

-- Uncomment to test after running seed:
-- SELECT COUNT(*) as total_companies FROM public.companies;
-- SELECT COUNT(*) as total_users FROM public.profiles;
-- SELECT COUNT(*) as total_attendance FROM public.attendance_logs;
-- SELECT first_name, last_name, email, role, status FROM public.profiles ORDER BY created_at DESC;
-- SELECT profile_id, date, clock_in_time, clock_out_time, status FROM public.attendance_logs ORDER BY date DESC;
